# Generated by Django 6.0.6 on 2026-06-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('unidade_medida', models.CharField(choices=[('KG', 'Quilograma'), ('LT', 'Litro'), ('UN', 'Unidade'), ('CX', 'Caixa')], default='KG', max_length=2, verbose_name='Unidade de Medida')),
                ('estoque_minimo', models.PositiveIntegerField(default=5, verbose_name='Estoque Mínimo (Alerta)')),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.fornecedor', verbose_name='Fornecedor Padrão')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_lote', models.CharField(max_length=50, verbose_name='Número/Código do Lote')),
                ('quantidade_inicial', models.PositiveIntegerField(verbose_name='Quantidade Comprada')),
                ('quantidade_atual', models.PositiveIntegerField(verbose_name='Quantidade Atual em Estoque')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produtos',
                'ordering': ['data_validade'],
            },
        ),
    ]
