# Generated by Django 6.0.6 on 2026-06-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0003_gradecurricular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Autor')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade do Autor')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Pequeno Histórico/Biografia do Autor')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Foto do Autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Editora')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site da Editora')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Livro')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas_livros/', verbose_name='Capa do Livro')),
                ('estado_conservacao', models.CharField(choices=[('EXC', 'Excelente'), ('REG', 'Regular (Marcas de uso)'), ('DAN', 'Danificado/Rasurado')], default='EXC', max_length=3, verbose_name='Estado de Conservação')),
                ('autores', models.ManyToManyField(related_name='livros', to='biblioteca.autor', verbose_name='Autores do Livro')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='biblioteca.categoria', verbose_name='Categoria do Livro')),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='biblioteca.editora', verbose_name='Editora do Livro')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(auto_now_add=True, verbose_name='Data de Saída')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateField(blank=True, null=True, verbose_name='Data da Devolução Real')),
                ('observacoes_danos', models.TextField(blank=True, null=True, verbose_name='Registro de Danos na Devolução')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='escola.aluno', verbose_name='Aluno')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário Responsável')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='biblioteca.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_saida'],
            },
        ),
    ]
