# Generated by Django 6.0.6 on 2026-06-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade Disponível'),
        ),
    ]
